import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=process.cwd(),site='https://1099taxcalcs.com/',read=file=>fs.readFileSync(path.join(root,file),'utf8'),write=(file,value)=>{const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,value,'utf8')},hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const cnameBefore=read('CNAME'),routes=[...read('sitemap.xml').matchAll(/<loc>https:\/\/1099taxcalcs\.com\/([^<]*)<\/loc>/g)].map(match=>match[1]),fileFor=route=>route?`${route}index.html`:'index.html',contentRoute=route=>(route.startsWith('calculators/')&&route!=='calculators/')||(route.startsWith('guides/')&&route!=='guides/')||(route.startsWith('deductions/')&&route!=='deductions/');
const planningScope=`<!-- phase7-planning-scope:start --><section class="notice phase7-planning-scope"><h2>Planning scope</h2><p>Results and examples are planning estimates and hypothetical illustrations. 1099TaxCalcs.com does not prepare or file tax returns and does not replace IRS, SSA, state, or local instructions. Tax rules can change, state and local taxes or specialized rules may be excluded, and eligibility depends on individual facts. Verify current official sources and consider a qualified professional when the decision is material or complex.</p></section><!-- phase7-planning-scope:end -->`;
let changed=0,adCount=0;
for(const route of routes){const file=fileFor(route);let html=read(file),before=html;
  const punctuationRepairs=[['\u00c3\u00a2\u00e2\u201a\u00ac\u00e2\u20ac\u009d','\u2014'],['\u00c3\u00a2\u00e2\u201a\u00ac\u00c5\u201c','\u201c'],['\u00c3\u00a2\u00e2\u201a\u00ac\u00c2\u009d','\u201d'],['\u00e2\u20ac\u201d','\u2014'],['\u00e2\u20ac\u0153','\u201c'],['\u00e2\u20ac\u009d','\u201d'],['\u00e2\u20ac\u201c','\u2013'],['\u00e2\u20ac\u00a6','\u2026']];for(const [broken,repaired]of punctuationRepairs)html=html.replaceAll(broken,repaired);
  html=html.replace(/<nav id="site-nav"(?![^>]*aria-label)/g,'<nav id="site-nav" aria-label="Main navigation"').replace(/<nav class="breadcrumbs"(?![^>]*aria-label)/g,'<nav class="breadcrumbs" aria-label="Breadcrumb"');
  html=html.replace(/<aside class="([^"]*\bad-slot\b[^"]*)"(?![^>]*data-ad-placeholder)/g,'<aside class="$1" data-ad-placeholder="true" aria-label="Advertisement placeholder"').replace(/aria-label="Advertisement placeholder"([^>]*)aria-label="Advertisement placeholder"/g,'aria-label="Advertisement placeholder"$1');adCount+=(html.match(/data-ad-placeholder="true"/g)||[]).length;
  if(contentRoute(route)){if(html.includes('<!-- phase7-planning-scope:start -->'))html=html.replace(/<!-- phase7-planning-scope:start -->[\s\S]*?<!-- phase7-planning-scope:end -->/,planningScope);else if(/<section class="notice"><h2>Tax disclaimer<\/h2>/.test(html))html=html.replace(/<section class="notice"><h2>Tax disclaimer<\/h2>/,planningScope+'<section class="notice"><h2>Tax disclaimer</h2>');else html=html.replace('</article>',planningScope+'</article>')}
  if(route.startsWith('guides/taxes-for-')){const audience=((html.match(/<h1[^>]*>Taxes for ([^<]+)<\/h1>/)||[])[1]||'').trim().toLowerCase();if(audience)html=html.replaceAll(`For taxes for ${audience}`,`For ${audience}`)}
  if(route==='contact/'){html=html.replace(/<!-- OWNER CONTACT CONFIGURATION:[\s\S]*?-->/,'').replace('<h2>Owner configuration required</h2>','<!-- OWNER CONTACT CONFIGURATION: Replace the launch-status sentence only after the owner approves a real public contact address. Do not publish a placeholder address. --><h2>Owner configuration required</h2>');if(!html.includes('Public contact information will be added before formal launch.'))html=html.replace('<p><strong>No active public email address or contact channel is currently configured.</strong>','<p><strong>Public contact information will be added before formal launch.</strong> No active public email address or contact channel is currently configured.</p><p>')}
  if(route.startsWith('guides/taxes-for-')){const description=(html.match(/<meta name="description" content="([^"]*)"/)||[])[1],h1=(html.match(/<h1[^>]*>([^<]*)<\/h1>/)||[])[1],income=(html.match(/earning independent-business income through ([^.]+)\./)||[])[1];if(description&&h1&&income){const revised=`${h1}: organize ${income.split(',').slice(0,2).join(',')}, business records, expenses, and tax reserves.`;html=html.replaceAll(description,revised)}}
  if(route.startsWith('deductions/')&&route!=='deductions/')html=html.replace(/Assuming every ([^<]+?) payment qualifies without reviewing business purpose\./,'Assuming every payment in this category qualifies without reviewing its business purpose.');
  if(html!==before){write(file,html);changed++}}
if(read('CNAME')!==cnameBefore||cnameBefore.trim()!=='1099TaxCalcs.com')throw new Error('CNAME changed or is invalid');
const sizes=['assets/css/styles.css','assets/js/main.js','assets/js/search-core.js','assets/js/site-search.js','data/search-index.js'].map(file=>`- ${file}: ${fs.statSync(path.join(root,file)).size.toLocaleString()} bytes`).join('\n');write('PRODUCTION-AUDIT-REPORT.md',`# Phase 7 Production Audit Report\n\nGenerated by \`build_phase7.mjs\`.\n\n- Sitemap pages: ${routes.length}\n- HTML pages updated by the final pass: ${changed}\n- Advertisement placeholders annotated: ${adCount}\n- CNAME SHA-256: \`${hash(cnameBefore)}\`\n\n## Production asset sizes\n\n${sizes}\n\n## Generator order\n\nWhen upstream content changes, run the applicable earlier generators, then always run \`node build_phase6.mjs\` and \`node build_phase7.mjs\` last. Phase 7 is idempotent and preserves every URL.\n`);console.log(`Phase 7 polished ${changed} of ${routes.length} sitemap pages; annotated ${adCount} ad placeholders; CNAME preserved.`);
