import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd(),site='https://1099taxcalcs.com/';
const write=(file,content)=>{const target=path.join(root,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content,'utf8')};
const walk=(directory,files=[])=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){if(['.git','tests','.edge-smoke','.edge-smoke2','node_modules'].includes(entry.name))continue;const absolute=path.join(directory,entry.name);if(entry.isDirectory())walk(absolute,files);else if(entry.name==='index.html')files.push(absolute)}return files};
const routeFor=file=>path.relative(root,file).split(path.sep).join('/').replace(/index\.html$/,'');
const strip=value=>String(value||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:amp|mdash|ndash|rarr|copy|quot|#39);/g,' ').replace(/\s+/g,' ').trim();
const extract=(html,re)=>((html.match(re)||[])[1]||'').trim();
const typeFor=route=>route.startsWith('calculators/')&&route!=='calculators/'?'calculator':route.startsWith('guides/taxes-for-')?'profession':route.startsWith('guides/')&&route!=='guides/'?'guide':route.startsWith('deductions/')&&route!=='deductions/'?'deduction':null;
const typeLabels={calculator:'Calculator',profession:'Profession Guide',guide:'Tax Guide',deduction:'Deduction Guide'};

const searchWidget=id=>`<!-- phase6-search:start --><form class="site-search" data-site-search role="search"><label for="${id}">Search calculators and guides</label><div class="site-search-controls"><input id="${id}" data-search-input type="search" autocomplete="off" placeholder="Search mileage, quarterly tax, photographers..."><select data-search-filter aria-label="Filter search results"><option value="all">All</option><option value="calculator">Calculators</option><option value="profession">Profession guides</option><option value="guide">Tax guides</option><option value="deduction">Deduction guides</option></select></div><p class="search-status" data-search-status aria-live="polite"></p><ul class="search-results" data-search-results></ul></form><!-- phase6-search:end -->`;
const searchScripts=prefix=>`<!-- phase6-search-scripts:start --><script defer src="${prefix}assets/js/search-core.js"></script><script defer src="${prefix}data/search-index.js"></script><script defer src="${prefix}assets/js/site-search.js"></script><!-- phase6-search-scripts:end -->`;
const replaceMarker=(html,start,end,block)=>html.includes(start)?html.replace(new RegExp(`${start}[\\s\\S]*?${end}`),block):html;
const listLinks=(prefix,items)=>`<ul class="resource-list">${items.map(([slug,label])=>`<li><a href="${prefix}${slug}/">${label}</a></li>`).join('')}</ul>`;

const calculatorLinks={
'self-employment-tax':{guides:[['what-is-self-employment-tax','What self-employment tax covers'],['how-self-employment-tax-is-calculated','How the calculation works']],prof:[['freelancers','Tax records for freelancers'],['independent-contractors','Planning for independent contractors']],ded:[['software-and-subscriptions','Software and subscription records'],['home-office-expenses','Home-office expense considerations']]},
'quarterly-tax':{guides:[['do-i-need-to-pay-quarterly-taxes','Quarterly-payment planning factors'],['estimated-tax-payments-explained','Estimated payments explained']],prof:[['gig-workers','Quarterly planning for gig workers'],['real-estate-agents','Uneven commission-income planning']],ded:[['retirement-contributions','Retirement contribution planning'],['self-employed-health-insurance','Health-insurance adjustment considerations']]},
'1099-take-home-pay':{guides:[['how-to-save-for-quarterly-taxes','Build a tax reserve'],['how-tax-deductions-reduce-taxable-income','Deductions and cash flow']],prof:[['freelancers','Freelancer income planning'],['consultants','Consultant take-home considerations']],ded:[['retirement-contributions','Retirement contributions'],['self-employed-health-insurance','Self-employed health insurance']]},
'1099-vs-w2':{guides:[['1099-vs-w2-taxes','1099 and W-2 tax differences'],['how-much-more-should-a-contractor-charge','Contractor compensation planning']],prof:[['consultants','Consultant compensation'],['software-developers','Software developer contract work']],ded:[['business-insurance','Contractor insurance costs'],['equipment-and-tools','Contractor equipment costs']]},
'mileage-deduction':{guides:[['standard-mileage-vs-actual-expenses','Compare vehicle methods'],['what-records-should-independent-contractors-keep','Mileage records to retain']],prof:[['rideshare-drivers','Rideshare mileage records'],['delivery-drivers','Delivery-driver vehicle use']],ded:[['vehicle-expenses','Vehicle expense guide'],['business-travel','Business travel distinctions']]},
'home-office-deduction':{guides:[['home-office-deduction-explained','Home-office methods explained'],['how-to-organize-business-expenses','Organize workspace records']],prof:[['web-developers','Developer workspace considerations'],['graphic-designers','Designer home-office records']],ded:[['home-office-expenses','Home-office expense guide'],['phone-and-internet','Phone and internet allocation']]},
'federal-income-tax':{guides:[['how-tax-deductions-reduce-taxable-income','How deductions affect income'],['how-to-pay-taxes-on-1099-income','Paying tax on 1099 income']],prof:[['independent-contractors','Independent-contractor tax planning'],['consultants','Consultant federal planning']],ded:[['retirement-contributions','Retirement contribution planning'],['self-employed-health-insurance','Health-insurance deduction considerations']]},
'schedule-c-profit':{guides:[['common-business-expenses-for-freelancers','Common expense categories'],['how-to-organize-business-expenses','Organize business expenses']],prof:[['online-sellers','Online seller income and costs'],['cleaning-businesses','Cleaning-business profit records']],ded:[['office-supplies','Office supply records'],['contract-labor','Contract-labor records']]},
'contractor-hourly-rate':{guides:[['how-to-set-a-freelance-hourly-rate','Set a sustainable freelance rate'],['how-much-more-should-a-contractor-charge','Contractor pricing factors']],prof:[['consultants','Consultant rate planning'],['web-developers','Web developer pricing']],ded:[['business-insurance','Insurance overhead'],['software-and-subscriptions','Software overhead']]},
'business-expense-deduction':{guides:[['difference-between-expense-and-deduction','Expense versus deduction'],['1099-tax-deductions','1099 deduction fundamentals']],prof:[['photographers','Photographer expense records'],['content-creators','Creator expense planning']],ded:[['equipment-and-tools','Equipment and tools'],['software-and-subscriptions','Software and subscriptions']]},
'1099-tax-reserve':{guides:[['how-to-save-for-quarterly-taxes','Reserve methods for irregular income'],['estimated-tax-payments-explained','Estimated payments and withholding']],prof:[['gig-workers','Gig-worker cash reserves'],['personal-trainers','Trainer income reserves']],ded:[['business-insurance','Business insurance planning'],['phone-and-internet','Communications costs']]},
'freelance-income':{guides:[['how-to-track-freelance-income','Track invoices and collections'],['1099-tax-checklist','Year-round 1099 checklist']],prof:[['content-creators','Creator revenue records'],['online-sellers','Online seller reconciliation']],ded:[['advertising-expenses','Advertising costs'],['contract-labor','Subcontractor costs']]}
};

const legacyGuides={
'how-to-calculate-1099-taxes':`<section class="section prose phase6-quality"><h2>Build the estimate in separate layers</h2><p>Start with gross business receipts, subtract supported business expenses, and use the resulting preliminary profit for self-employment-tax planning. Estimate federal income tax separately, then account for withholding, credits, and payments already made.</p><h2>Why separation matters</h2><p>Self-employment tax, federal income tax, state planning, and cash reserves answer different questions. Combining them into one unexplained percentage hides the assumptions that most affect the result.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A consultant reconciles $82,000 of receipts and $14,000 of supported costs before using the self-employment and federal-income-tax calculators separately.</p></section>`,
'how-much-to-set-aside-for-1099-taxes':`<section class="section prose phase6-quality"><h2>Use a projection, not a universal percentage</h2><p>A useful reserve reflects net business income, household withholding, filing status, credits, state or local assumptions, and payments already made. A payment-by-payment percentage can support cash flow, but it should be reconciled to an annual projection.</p><h2>Keep reserve cash distinct</h2><p>A reserve is money set aside; it is not an estimated payment, a return filing, or a safe-harbor conclusion. Seasonal workers may need more frequent projection updates.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A creator revises the annual estimate after a large sponsorship instead of continuing to reserve the same flat amount from every deposit.</p></section>`,
'how-to-calculate-freelance-hourly-rate':`<section class="section prose phase6-quality"><h2>Translate annual needs into billable revenue</h2><p>Estimate working weeks and hours, subtract time off and administration, and apply realistic billable utilization. Add business overhead, benefit replacement, tax reserves, and contingency before dividing by billable hours.</p><h2>Minimum sustainable rate versus market rate</h2><p>The calculation produces a planning floor, not a guaranteed market price. Experience, scope, demand, payment terms, and client risk still affect a quote.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A developer models 1,250 billable hours rather than dividing annual pay by 2,080 total hours.</p></section>`,
'schedule-c-income-and-expenses':`<section class="section prose phase6-quality"><h2>Reconcile business income before categorizing costs</h2><p>Gross receipts can include direct payments, platform activity, and other business income. Returns, allowances, cost of goods sold, and operating expenses affect different parts of a preliminary Schedule C model.</p><h2>Flag items needing separate treatment</h2><p>Inventory, depreciation, home-office costs, meals, vehicle use, and business losses can require rules beyond a simple category total.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> An online seller reconciles customer orders to refunds, platform fees, and deposits before reviewing inventory treatment.</p></section>`,
'business-expense-tax-deductions':`<section class="section prose phase6-quality"><h2>Spending and tax treatment are different</h2><p>A business purchase may be currently deductible, partly business, reimbursed, capitalized, depreciated, treated as inventory, or personal. Start with business purpose and records, then determine the preliminary planning amount.</p><h2>Do not equate cost with refund</h2><p>A $1,000 purchase does not normally create a $1,000 refund. A supported deduction generally reduces an income measure, and the estimated tax effect depends on other facts.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A photographer records a camera purchase separately from routine supplies and reviews business use and depreciation rules.</p></section>`,
'1099-quarterly-tax-planning':`<section class="section prose phase6-quality"><h2>Plan around payment periods and current facts</h2><p>Project income tax and self-employment tax, then subtract expected withholding, credits, and payments already made. Verify the current Form 1040-ES dates and instructions rather than relying on last year.</p><h2>Uneven income needs extra care</h2><p>Equal installments may not fit seasonal or irregular earnings. Annualized-income methods and safe-harbor rules require complete inputs and official guidance.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A real estate agent updates the projection after a strong third quarter and retains each payment confirmation.</p></section>`,
'1099-vs-w2-compensation':`<section class="section prose phase6-quality"><h2>Compare economic value, not labels</h2><p>Include salary or contractor compensation, payroll-tax mechanics, benefits, paid time off, insurance, equipment, overhead, and nonbillable time. Use consistent federal and state planning assumptions on both sides.</p><h2>Classification is a legal-fact question</h2><p>A worker and payer cannot choose classification solely by preferring Form 1099 or Form W-2 treatment. Review the actual relationship and current guidance.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A designer compares an employee offer with a contract proposal after valuing health benefits and unpaid administration.</p></section>`,
'freelancer-invoice-income':`<section class="section prose phase6-quality"><h2>Reconcile billed, collected, and deposited amounts</h2><p>Track invoices, collections, platform fees, processing fees, refunds, chargebacks, contractor costs, and separately collected sales tax. Net bank deposits alone can hide important activity.</p><h2>Accounting treatment still requires review</h2><p>Unpaid invoices are not automatically deductible, and cash-versus-accrual treatment depends on the applicable accounting method and facts.</p><h2>Hypothetical example</h2><p><strong>Hypothetical:</strong> A freelancer reconciles twelve invoices to processor statements and bank deposits before estimating spendable income.</p></section>`
};

const trustSections={
'about/':`<section class="section prose phase6-trust"><p>1099TaxCalcs.com provides static, browser-based planning calculators and plain-language education for self-employed work. It does not prepare or file tax returns and does not create a professional-client relationship.</p><h2>How the site works</h2><ul><li>Calculator entries stay in the browser and are not sent to a server.</li><li>Federal assumptions are dated and linked to official sources.</li><li>State and local amounts remain user-entered unless a future tool implements verified jurisdiction-specific rules.</li><li>Examples are hypothetical and never presented as taxpayer outcomes.</li></ul><h2>Corrections and limitations</h2><p>Tax rules and official publications change. Verify current sources and use the contact page to review how a correction channel will be configured; no active public contact address is currently represented.</p></section>`,
'methodology/':`<section class="section prose phase6-trust"><p><strong>Tax-year scope:</strong> Calculator defaults use the verified year recorded in the shared tax configuration. State and local rates remain user-entered planning assumptions.</p><h2>Formula and source process</h2><p>Annual values are stored with source URLs, effective dates, verification status, and review notes. Shared calculation functions retain decimals while most money displays are rounded to avoid false precision.</p><h2>Privacy and output scope</h2><p>Calculations run locally in the browser. Inputs are not sent, stored in cookies, placed in URLs, or saved to local storage. Results are planning estimates, not returns, filings, eligibility determinations, or penalty-protection conclusions.</p><h2>Corrections</h2><p>A material correction should update the canonical configuration or formula, generator source, affected generated pages, tests, methodology, and review date. Official-source links must be checked during annual review.</p></section>`,
'editorial-policy/':`<section class="section prose phase6-trust"><p>Content must use plain language, distinguish planning from individualized advice, and link tax-specific claims to official government sources.</p><h2>Review standards</h2><ul><li>No invented rates, limits, deadlines, eligibility conclusions, credentials, reviews, or outcome claims.</li><li>Hypothetical examples must be labeled and must not imitate real taxpayer stories.</li><li>Profession and expense pages must contain facts specific to their subject rather than keyword substitutions.</li><li>Year-sensitive statements require annual and material-change review.</li></ul><h2>Corrections</h2><p>Corrections should be reflected in source data, generated pages, related calculators or guides, tests, and the visible review date. The contact page explains the current owner-configuration status.</p></section>`,
'disclaimer/':`<section class="section prose phase6-trust"><p>1099TaxCalcs.com provides educational content and browser-based planning estimates. It does not provide tax, legal, accounting, financial, or worker-classification advice and is not endorsed by the IRS or SSA.</p><h2>What results do not establish</h2><p>Results do not prepare or file a return, prove deduction eligibility, guarantee a refund or balance, determine estimated-tax penalty protection, or resolve state and local obligations.</p><h2>Verify before acting</h2><p>Tax treatment depends on facts not collected here and rules that change. Review current official guidance and consider a qualified professional for complex or high-stakes decisions.</p></section>`,
'privacy/':`<section class="section prose phase6-trust"><p>Calculator inputs and search queries are processed locally in the browser. The site does not send financial entries or search terms to a server and does not use analytics, tracking, cookies, accounts, or local storage.</p><h2>Static search and advertisements</h2><p>The search index is a static file containing public page titles, short descriptions, types, and keywords. Advertisement boxes are placeholders only; no advertising code is installed.</p><h2>Future changes</h2><p>If a hosted contact service, analytics, or advertising is introduced later, this policy must be updated before activation and any required choices must be implemented.</p></section>`,
'contact/':`<section class="section prose phase6-trust"><p>This static website has no contact form or backend, and visitors should never submit financial or sensitive tax information through the site.</p><h2>Owner configuration required</h2><p><strong>No active public email address or contact channel is currently configured.</strong> The owner must approve and add a real channel before the site presents one as available. No placeholder address is treated as active.</p><h2>Correction reports</h2><p>When an owner-approved channel is configured, correction reports should identify the page URL, the statement or behavior at issue, and an official supporting source—without including private taxpayer information.</p></section>`,
'terms/':`<section class="section prose phase6-trust"><p>By using this site, you acknowledge that its calculators and articles provide general planning information that may be incomplete, outdated, or inapplicable to your circumstances.</p><h2>No filing or professional relationship</h2><p>The site does not prepare or file returns and does not create an accountant-client, attorney-client, adviser, or fiduciary relationship. You remain responsible for verifying filings, payments, classifications, elections, deductions, and deadlines.</p><h2>Privacy-conscious use</h2><p>Calculations and static search run in the browser. Do not enter sensitive identifiers; the calculators do not need names, Social Security numbers, bank credentials, or account access.</p></section>`
};

let files=walk(root),records=[];
for(const file of files){const route=routeFor(file),type=typeFor(route);if(!type)continue;const html=fs.readFileSync(file,'utf8'),title=extract(html,/<h1[^>]*>([\s\S]*?)<\/h1>/),description=extract(html,/<meta name="description" content="([^"]*)"/),headings=[...html.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/g)].slice(0,6).map(match=>strip(match[1])).join(' '),category=route.split('/')[0];records.push({title:strip(title),url:`/${route}`,type,description:strip(description),keywords:strip(`${route.replaceAll('-',' ')} ${headings}`),category});}
records.sort((a,b)=>a.title.localeCompare(b.title));write('data/search-index.js',`window.SITE_SEARCH_INDEX=${JSON.stringify(records)};\n`);

for(const file of files){let html=fs.readFileSync(file,'utf8'),route=routeFor(file),depth=route.split('/').filter(Boolean).length,prefix='../'.repeat(depth);
  html=html.replace(/<!-- phase6-search-scripts:start -->[\s\S]*?<!-- phase6-search-scripts:end -->/g,'').replace('</head>',`${searchScripts(prefix)}</head>`);
  html=html.replace(/<!-- phase6-search:start -->[\s\S]*?<!-- phase6-search:end -->/g,'');
  html=html.replace('</nav>',`</nav>${searchWidget(`siteSearch-${route.replaceAll('/','-')||'home'}`)}`);
  const type=typeFor(route);
  if((type==='guide'||type==='profession'||type==='deduction')&&!html.includes('Last reviewed:'))html=html.replace('</header>','<p class="fine"><strong>Last reviewed:</strong> July 18, 2026</p></header>');
  if(type==='calculator'){
    const slug=route.split('/')[1],set=calculatorLinks[slug];if(set){const block=`<!-- phase6-learning:start --><section class="section phase6-learning"><div class="section-heading"><div><p class="eyebrow">Learn and prepare</p><h2>Records and explanations for this estimate</h2></div><p>Use these guides to improve inputs and review important limitations.</p></div><div class="card-grid"><div class="card"><h3>Educational guides</h3>${listLinks('../../guides/',set.guides)}</div><div class="card"><h3>Profession guides</h3>${listLinks('../../guides/taxes-for-',set.prof)}</div><div class="card"><h3>Expense guides</h3>${listLinks('../../deductions/',set.ded)}</div></div></section><!-- phase6-learning:end -->`;html=replaceMarker(html,'<!-- phase6-learning:start -->','<!-- phase6-learning:end -->',block);if(!html.includes('<!-- phase6-learning:start -->'))html=html.replace(/<section class="notice"><h2>Tax disclaimer<\/h2>/,block+'<section class="notice"><h2>Tax disclaimer</h2>');if(!html.includes('<!-- phase6-learning:start -->'))html=html.replace('</article>',block+'</article>');}
  }
  if(type==='profession'){
    const title=strip(extract(html,/<h1[^>]*>([\s\S]*?)<\/h1>/));html=html.replace('Start with supported net business profit, not gross deposits. Self-employment tax is distinct from federal income tax. Withholding, credits, W-2 wages, filing status, and household facts can affect the broader projection.',`For ${title.toLowerCase()}, reconcile each stated income stream to invoices, platform or client records, and deposits before estimating net business profit. Self-employment tax remains distinct from federal income tax, while withholding, credits, W-2 wages, and household facts affect the broader projection.`).replace('Consider qualified help for entity choices, workers, inventory, depreciation, multistate work, amended records, classification questions, or facts that do not fit the calculators.',`For ${title.toLowerCase()}, professional review may be useful when contracts, workers, equipment, inventory, multistate activity, classification, or unusual payments do not fit the records and calculators described here.`);
  }
  if(type==='guide'){
    const title=strip(extract(html,/<h1[^>]*>([\s\S]*?)<\/h1>/));html=html.replace('This guide does not calculate every credit, deduction, special tax, state or local rule, accounting method, entity rule, penalty exception, or eligibility limitation. It does not prepare or file a return.',`${title} focuses on its stated planning question. It does not calculate every credit, deduction, special tax, state or local rule, accounting method, entity rule, penalty exception, or eligibility limitation, and it does not prepare or file a return.`).replace('Qualified help may be useful for multiple businesses, employees or subcontractors, inventory, depreciation, entity elections, multistate work, amended records, large income changes, notices, or facts that do not fit the linked calculators.',`Professional review may be useful when the ${title.toLowerCase()} question involves multiple businesses, workers, inventory, depreciation, entity elections, multistate activity, notices, amended records, or facts outside the linked calculators.`);
    const slug=route.split('/')[1],quality=legacyGuides[slug];if(quality){const re=/(<header class="page-head">[\s\S]*?<\/header>)([\s\S]*?)(<aside class="ad-slot content-ad")/;html=html.replace(re,`$1${quality}$3`)}
  }
  if(trustSections[route]){const re=/<section class="section prose">[\s\S]*?<\/section>/;html=html.replace(re,trustSections[route]);}
  if(route==='guides/'){
    const legacy=Object.keys(legacyGuides).map(slug=>{const record=records.find(item=>item.url===`/guides/${slug}/`);return `<a class="link-card filter-item" data-search="${strip(`${record.title} ${record.description}`).toLowerCase()}" href="${slug}/"><p class="eyebrow">Focused planning guide</p><h3>${record.title}</h3><p>${record.description}</p><span>Read guide &rarr;</span></a>`}).join('');const block=`<!-- phase6-legacy-guides:start --><section class="section"><h2>Focused planning guides</h2><div class="card-grid">${legacy}</div></section><!-- phase6-legacy-guides:end -->`;html=replaceMarker(html,'<!-- phase6-legacy-guides:start -->','<!-- phase6-legacy-guides:end -->',block);if(!html.includes('<!-- phase6-legacy-guides:start -->'))html=html.replace('<section class="section" id="profession-guides">',block+'<section class="section" id="profession-guides">');
  }
  if(route==='calculators/'){
    html=html.replace(/<a class="link-card(?! filter-item)"/g,'<a class="link-card filter-item"');html=html.replace(/<a class="link-card filter-item"([^>]*)>/g,(match,attrs)=>{const href=(attrs.match(/href="([^"]+)"/)||[])[1]||'';return `<a class="link-card filter-item" data-search="${strip(href.replaceAll('-',' '))}"${attrs}>`});const block=`<!-- phase6-calculator-filter:start --><div class="card directory-filter"><label for="guideFilter"><strong>Filter calculators</strong></label><input id="guideFilter" type="search" placeholder="Try quarterly, mileage, income, or rate" aria-describedby="guideFilterHelp"><p class="hint" id="guideFilterHelp">Filter the calculator cards shown below.</p><p class="fine" id="filterStatus" aria-live="polite"></p></div><section class="notice start-here"><h2>Start here</h2><p>New to 1099 planning? Begin with the <a href="self-employment-tax/">Self-Employment Tax Calculator</a>, then use the quarterly or reserve tools for cash planning.</p></section><!-- phase6-calculator-filter:end -->`;html=replaceMarker(html,'<!-- phase6-calculator-filter:start -->','<!-- phase6-calculator-filter:end -->',block);if(!html.includes('<!-- phase6-calculator-filter:start -->'))html=html.replace('</header>',`</header>${block}`);if(!html.includes('content-filter.js'))html=html.replace('</head>',`<script defer src="../assets/js/content-filter.js"></script></head>`);
  }
  if(route==='guides/'||route==='deductions/')html=html.replace('</header>',`</header><section class="notice start-here"><h2>Start here</h2><p>${route==='guides/'?'Begin with “What Is Self-Employment Tax?” for fundamentals, or filter by your planning question.':'Begin with the category that matches your records, then verify eligibility and special treatment before calculating.'}</p></section>`);
  if(route===''){
    const block=`<!-- phase6-home-search:start --><section class="section" id="site-search"><div class="section-heading"><div><p class="eyebrow">Search the complete website</p><h2>Find a calculator or focused guide</h2></div><p>Search runs only in your browser. Queries are not stored or transmitted.</p></div>${searchWidget('siteSearchHome')}</section><!-- phase6-home-search:end -->`;html=replaceMarker(html,'<!-- phase6-home-search:start -->','<!-- phase6-home-search:end -->',block);if(!html.includes('<!-- phase6-home-search:start -->'))html=html.replace('<section class="notice"><h2>Important tax disclaimer</h2>',block+'<section class="notice"><h2>Important tax disclaimer</h2>');
  }
  write(path.relative(root,file),html);
}

files=walk(root);const publicRoutes=new Set([...fs.readFileSync(path.join(root,'sitemap.xml'),'utf8').matchAll(/<loc>https:\/\/1099taxcalcs\.com\/([^<]*)<\/loc>/g)].map(match=>match[1]));const incoming=new Map([...publicRoutes].map(route=>[route,0]));const broken=[];
for(const file of files){const route=routeFor(file),html=fs.readFileSync(file,'utf8');if(!publicRoutes.has(route))continue;for(const match of html.matchAll(/href="([^"]+)"/g)){const href=match[1];if(/^(?:https?:|mailto:|tel:|#)/.test(href))continue;const target=new URL(href,site+route).pathname.replace(/^\//,'');if(path.posix.extname(target))continue;const normalized=target&&!target.endsWith('/')?`${target}/`:target;if(publicRoutes.has(normalized))incoming.set(normalized,incoming.get(normalized)+1);else broken.push(`${route} -> ${href}`);}}
const orphans=[...incoming].filter(([route,count])=>route&&count===0).map(([route])=>route);write('INTERNAL-LINK-REPORT.md',`# Internal Link Validation Report\n\nGenerated by \`build_phase6.mjs\`.\n\n- Sitemap pages checked: ${publicRoutes.size}\n- Broken internal page links: ${broken.length}\n- Orphan pages: ${orphans.length}\n\n${broken.length?`## Broken links\n\n${broken.map(item=>`- ${item}`).join('\n')}\n`:''}${orphans.length?`## Orphan pages\n\n${orphans.map(item=>`- ${item}`).join('\n')}\n`:'Every sitemap page receives at least one internal link.\n'}`);
write('PROJECT-INVENTORY.md',`# Public Page Inventory\n\n- Public sitemap pages: ${publicRoutes.size}\n- Homepage: 1\n- Calculator directory: 1\n- Calculators: 12\n- Guide directory: 1\n- Profession guides: 20\n- Core education guides: 20\n- Earlier focused guides: 8\n- Deduction directory: 1\n- Deduction guides: 15\n- Supporting, legal, trust, and directory pages: ${publicRoutes.size-79}\n- Static search records: ${records.length}\n\nRun Phase 1, Phase 4, and Phase 5 generators only when their sources change, then always run \`node build_phase6.mjs\` last. Phase 6 adds search, cross-links, trust copy, directory enhancements, and the generated link report without changing public URLs.\n`);
console.log(`Phase 6 generated ${records.length} search records across ${publicRoutes.size} public sitemap pages; ${broken.length} broken links and ${orphans.length} orphan pages.`);
