import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root=path.resolve(import.meta.dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),tests=[],test=(name,value)=>tests.push([name,Boolean(value)]);
const raw=read('data/search-index.js'),records=JSON.parse(raw.replace(/^window\.SITE_SEARCH_INDEX=/,'').replace(/;\s*$/,'')),context={};vm.createContext(context);vm.runInContext(read('assets/js/search-core.js'),context);const core=context.SiteSearchCore;
const byType=type=>records.filter(record=>record.type===type);
test('75 compact search records',records.length===75&&Buffer.byteLength(raw)<50000);
test('12 calculator records',byType('calculator').length===12);
test('20 profession records',byType('profession').length===20);
test('28 tax guide records',byType('guide').length===28);
test('15 deduction records',byType('deduction').length===15);
test('unique search URLs',new Set(records.map(record=>record.url)).size===records.length);
test('records have required fields',records.every(record=>record.title&&record.url&&record.type&&record.description&&record.keywords));
test('vehicle search finds relevant types',new Set(core.search(records,'vehicle').map(record=>record.type)).size>=3);
test('profession filter',core.search(records,'driver','profession').every(record=>record.type==='profession')&&core.search(records,'driver','profession').length>0);
test('calculator filter',core.search(records,'tax','calculator').every(record=>record.type==='calculator')&&core.search(records,'tax','calculator').length>0);
test('deduction filter',core.search(records,'insurance','deduction').every(record=>record.type==='deduction')&&core.search(records,'insurance','deduction').length>0);
test('empty search',core.search(records,'').length===0);
test('no-result search',core.search(records,'zzzz-no-result-zzzz').length===0);
const index=read('index.html'),calculators=read('calculators/index.html'),guides=read('guides/index.html'),deductions=read('deductions/index.html'),css=read('assets/css/styles.css'),searchJs=read('assets/js/site-search.js');
test('homepage search and concise discovery',index.includes('Search the complete website')&&index.includes('data-site-search'));
test('calculator directory filter and categories',calculators.includes('Filter calculators')&&['Tax Estimation','Quarterly Planning','Income and Take-Home Pay','Contractor Pricing','Business Income','Expenses and Deductions'].every(value=>calculators.includes(`<h2>${value}</h2>`)));
test('guide categories',['Getting Started','Quarterly Tax Planning','Income and Pricing','Expenses and Deductions','Recordkeeping','Profession guides'].every(value=>guides.includes(`<h2>${value}</h2>`)));
test('deduction categories',['Operating Expenses','Professional Services','Travel and Vehicle','Workspace','Equipment and Technology','Benefits and Long-Term Planning'].every(value=>deductions.includes(`<h2>${value}</h2>`)));
test('search output uses textContent',searchJs.includes('textContent=record.title')&&searchJs.includes('textContent=record.description')&&!searchJs.includes('innerHTML'));
test('search does not store or transmit',!/(fetch\(|XMLHttpRequest|localStorage|sessionStorage|document\.cookie)/.test(searchJs));
test('search accessibility',searchJs.includes("aria-live")===false&&index.includes('data-search-status aria-live="polite"'));
test('mobile search styles',css.includes('@media(max-width:560px)')&&css.includes('.site-search-controls{grid-template-columns:1fr}'));
test('overflow protections',css.includes('overflow-wrap:anywhere')&&css.includes('.table-wrap{overflow-x:auto'));
test('reduced motion',css.includes('prefers-reduced-motion:reduce'));
test('trust pages updated',['about','methodology','editorial-policy','disclaimer','privacy','contact','terms'].every(slug=>read(`${slug}/index.html`).includes('phase6-trust')));
test('contact has no invented address',read('contact/index.html').includes('No active public email address')&&!read('contact/index.html').includes('mailto:'));
test('calculator learning paths',['self-employment-tax','quarterly-tax','1099-take-home-pay','1099-vs-w2','mileage-deduction','home-office-deduction','federal-income-tax','schedule-c-profit','contractor-hourly-rate','business-expense-deduction','1099-tax-reserve','freelance-income'].every(slug=>read(`calculators/${slug}/index.html`).includes('phase6-learning')));
test('legacy guides receive directory links',read('guides/index.html').includes('phase6-legacy-guides'));
test('zero link defects',read('INTERNAL-LINK-REPORT.md').includes('Broken internal page links: 0')&&read('INTERNAL-LINK-REPORT.md').includes('Orphan pages: 0'));
test('CNAME exact',read('CNAME').trim()==='1099TaxCalcs.com');
for(const [name,ok]of tests)console.log(`${ok?'PASS':'FAIL'}: ${name}`);if(tests.some(([,ok])=>!ok))process.exit(1);console.log(`PASS: ${tests.length} Phase 6 search, directory, accessibility, trust, mobile, and preservation tests.`);
