import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(import.meta.dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const slugs=['what-is-self-employment-tax','how-self-employment-tax-is-calculated','how-to-pay-taxes-on-1099-income','when-do-1099-workers-pay-taxes','do-i-need-to-pay-quarterly-taxes','how-to-save-for-quarterly-taxes','estimated-tax-payments-explained','1099-tax-deductions','common-business-expenses-for-freelancers','difference-between-expense-and-deduction','how-tax-deductions-reduce-taxable-income','standard-mileage-vs-actual-expenses','home-office-deduction-explained','1099-vs-w2-taxes','how-much-more-should-a-contractor-charge','how-to-set-a-freelance-hourly-rate','how-to-track-freelance-income','how-to-organize-business-expenses','what-records-should-independent-contractors-keep','1099-tax-checklist'];
const tests=[];const test=(name,value)=>tests.push([name,Boolean(value)]);const count=(s,re)=>(s.match(re)||[]).length;
for(const slug of slugs){const file=`guides/${slug}/index.html`;test(`${slug}: exists`,fs.existsSync(path.join(root,file)));const html=read(file);test(`${slug}: one H1`,count(html,/<h1\b/g)===1);test(`${slug}: metadata`,count(html,/<title>/g)===1&&/meta name="description"/.test(html)&&/property="og:title"/.test(html));test(`${slug}: canonical`,html.includes(`href="https://1099taxcalcs.com/guides/${slug}/"`));test(`${slug}: explanatory sections`,['Why this matters for 1099 workers','Step-by-step explanation','Hypothetical example','Common mistakes','What this guide does not cover','When professional help may be appropriate'].every(x=>html.includes(x)));test(`${slug}: sources, disclaimer, review date`,html.includes('Official sources and annual review')&&html.includes('Tax disclaimer')&&html.includes('Last reviewed:'));test(`${slug}: calculators`,count(html,/href="\.\.\/\.\.\/calculators\//g)>=2);test(`${slug}: professions`,count(html,/href="\.\.\/taxes-for-/g)>=2);test(`${slug}: education`,count(html,/href="\.\.\/[a-z0-9-]+\//g)>=2)}
const sitemap=read('sitemap.xml'),directory=read('guides/index.html'),home=read('index.html');test('all URLs in sitemap',slugs.every(x=>sitemap.includes(`https://1099taxcalcs.com/guides/${x}/`)));test('all guides in directory',slugs.every(x=>directory.includes(`href="${x}/"`)));test('requested directory groups',['Getting Started','Quarterly Tax Planning','Deductions and Expenses','Income and Pricing','Profession guides'].every(x=>directory.includes(`<h2>${x}</h2>`)));test('six homepage education links',count(home,/class="link-card" href="guides\/(?:what-is-self-employment-tax|how-to-pay-taxes-on-1099-income|do-i-need-to-pay-quarterly-taxes|1099-tax-deductions|how-to-set-a-freelance-hourly-rate|1099-tax-checklist)\//g)===6);test('CNAME exact',read('CNAME').trim()==='1099TaxCalcs.com');
for(const [name,ok]of tests)console.log(`${ok?'PASS':'FAIL'}: ${name}`);if(tests.some(x=>!x[1]))process.exit(1);console.log(`PASS: ${tests.length} Phase 5B guide tests.`);
